export const site = {
  name: "Rachat Bijoux Courchevel",
  brandName: "Rachat Bijoux Courchevel",
  legalName: "Rachat Bijoux Courchevel — Maison Obagem",
  domain: "rachat-bijoux-courchevel.site",
  url: "https://rachat-bijoux-courchevel.site",
  city: "Courchevel",
  citySlug: "courchevel",
  postalCode: "73120",
  department: "Savoie (73)",
  region: "Auvergne-Rhône-Alpes",
  regionContext: "Courchevel (73120) — Courchevel 1850, Jardin Alpin, Bellecôte, Chenus, Moriond 1650, Village 1550, Le Praz 1300, La Tania, Méribel et Les 3 Vallées",
  tagline: "Cabinet d'Expertise Gemmologique & Rachat de Haute Joaillerie, Diamants et Montres de Prestige à Courchevel 1850",
  description: "Rachat Bijoux Courchevel : Cabinet d'expertise gemmologique indépendante et rachat immédiat de diamants certifiés (GIA, HRD, SSEF) selon le cours officiel Rapaport, haute joaillerie signée (Cartier, Van Cleef & Arpels, Boucheron, Graff, Bulgari, Chopard), montres de prestige (Rolex, Patek Philippe, Richard Mille, Audemars Piguet) et or d'investissement. Salons privés confidentiels à Courchevel 1850 et déplacements sécurisés en chalets privés, palaces (Les Airelles, Cheval Blanc, K2) et résidences alpines des 3 Vallées et Megève. Virement bancaire instantané en EUR.",
  port: 3810,

  phone: "+33 1 48 87 81 44",
  phoneDisplay: "+33 1 48 87 81 44",
  phoneIntl: "+33148878144",
  whatsappPhone: "+33148878144",
  email: "contact@obagem.fr",
  whatsappUrl: "https://wa.me/33148872337",

  address: {
    street: "Rue du Rocher",
    postalCode: "73120",
    city: "Courchevel",
    region: "Savoie",
    country: "FR",
    geo: { lat: 45.4150, lng: 6.6340 },
  },

  openingHours: [
    { day: "Lundi - Vendredi", hours: "09:30 - 19:00" },
    { day: "Samedi", hours: "10:00 - 18:00 (sur rendez-vous)" },
    { day: "Dimanche", hours: "Sur rendez-vous VIP" },
  ],

  stats: [
    { value: "40+", label: "Ans d'Expertise" },
    { value: "100%", label: "Virement Immédiat en EUR" },
    { value: "GIA / SSEF", label: "Gemmologues Diplômés" },
    { value: "Rapaport", label: "Cours Mondial en Direct" },
  ],

  areasServed: [
    "Courchevel",
    "Courchevel 1850",
    "Jardin Alpin",
    "Bellecôte",
    "Rue du Rocher",
    "Rue Park City",
    "Nogentil",
    "Chenus",
    "Courchevel Moriond 1650",
    "Courchevel Village 1550",
    "Courchevel Le Praz 1300",
    "La Tania",
    "Méribel",
    "Val Thorens",
    "Les Menuires",
    "Les 3 Vallées",
    "Megève",
    "Chamonix-Mont-Blanc",
    "Savoie",
  ],
};
